<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="Pragti" failures="14" tests="14" name="Test(failed)" time="0.534" errors="0" timestamp="2024-06-12T13:03:56 IST">
  <testcase classname="onlyfailedtcexecute.New2Test" name="fkkllTest" time="0.12">
    <failure type="java.lang.AssertionError" message="expected [8] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [5]
at onlyfailedtcexecute.New2Test.fkkllTest(New2Test.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- fkkllTest -->
  <testcase classname="onlyfailedtcexecute.New2Test" name="f8Test" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [8] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [5]
at onlyfailedtcexecute.New2Test.f8Test(New2Test.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- f8Test -->
  <testcase classname="onlyfailedtcexecute.New2Test" name="fTest" time="0.005">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at onlyfailedtcexecute.New2Test.fTest(New2Test.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- fTest -->
  <testcase classname="onlyfailedtcexecute.New2Test" name="fkklliTest" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [8] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [5]
at onlyfailedtcexecute.New2Test.fkklliTest(New2Test.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- fkklliTest -->
  <testcase classname="onlyfailedtcexecute.New2Test" name="f0Test" time="0.005">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at onlyfailedtcexecute.New2Test.f0Test(New2Test.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- f0Test -->
  <testcase classname="onlyfailedtcexecute.New1Test" name="fkkllTest" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [8] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [5]
at onlyfailedtcexecute.New1Test.fkkllTest(New1Test.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- fkkllTest -->
  <testcase classname="onlyfailedtcexecute.New1Test" name="f8Test" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [8] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [5]
at onlyfailedtcexecute.New1Test.f8Test(New1Test.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- f8Test -->
  <testcase classname="onlyfailedtcexecute.New1Test" name="fTest" time="0.006">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at onlyfailedtcexecute.New1Test.fTest(New1Test.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- fTest -->
  <testcase classname="onlyfailedtcexecute.New1Test" name="f0Test" time="0.006">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at onlyfailedtcexecute.New1Test.f0Test(New1Test.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- f0Test -->
  <testcase classname="onlyfailedtcexecute.New3Test" name="fTest" time="0.005">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at onlyfailedtcexecute.New3Test.fTest(New3Test.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- fTest -->
  <testcase classname="onlyfailedtcexecute.New3Test" name="f8Test" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [8] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [5]
at onlyfailedtcexecute.New3Test.f8Test(New3Test.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- f8Test -->
  <testcase classname="onlyfailedtcexecute.New3Test" name="fkkllyyTest" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [8] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [5]
at onlyfailedtcexecute.New3Test.fkkllyyTest(New3Test.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- fkkllyyTest -->
  <testcase classname="onlyfailedtcexecute.New3Test" name="fkkllTest" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [8] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [5]
at onlyfailedtcexecute.New3Test.fkkllTest(New3Test.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- fkkllTest -->
  <testcase classname="onlyfailedtcexecute.New3Test" name="f0Test" time="0.006">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at onlyfailedtcexecute.New3Test.f0Test(New3Test.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- f0Test -->
  <testcase classname="onlyfailedtcexecute.New3Test" name="fkTest" time="0.0">
    <ignored/>
  </testcase> <!-- fkTest -->
  <testcase classname="onlyfailedtcexecute.New1Test" name="fkTest" time="0.0">
    <ignored/>
  </testcase> <!-- fkTest -->
  <testcase classname="onlyfailedtcexecute.New2Test" name="fkTest" time="0.0">
    <ignored/>
  </testcase> <!-- fkTest -->
  <testcase classname="onlyfailedtcexecute.New2Test" name="ffTest" time="0.0">
    <ignored/>
  </testcase> <!-- ffTest -->
  <testcase classname="onlyfailedtcexecute.New1Test" name="ffTest" time="0.0">
    <ignored/>
  </testcase> <!-- ffTest -->
  <testcase classname="onlyfailedtcexecute.New3Test" name="ffTest" time="0.0">
    <ignored/>
  </testcase> <!-- ffTest -->
</testsuite> <!-- Test(failed) -->
